AllCops:
  NewCops: enable
  # Output extra information for each offense to make it easier to diagnose:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  # RuboCop enforces rules depending on the oldest version of Ruby which
  # your project supports:
  TargetRubyVersion: 2.6

# The default max line length is 80 characters
Layout/LineLength:
  Max: 120

# The DSL for RSpec makes it very hard to limit block length:
Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "*.gemspec"
